version: "3.8"
services:
  hashtopolis-web-ui:
    container_name: devcontainer-hashtopolis-web-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    networks:
      - hashtopolis_dev
    command: sleep infinity

networks:
  hashtopolis_dev:
    # This network will also be used by the python-agent
    name: hashtopolis_dev
